name: bootstrap_dart_example
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  mobx:
  incremental_dom_bindings: ^2.1.0
  universal_html: ^2.0.8
  deact:
    git:
      url: https://github.com/juancastillo0/deact.git
      ref: 537a9e600641a0aed15b7811c61f80fe4c0c0d12
    # path: ../deact
  deact_bootstrap:
    path: ../packages/deact_bootstrap
  bootstrap_dart:
    path: ../
  shelf:
  shelf_router:
  shelf_hotreload:
  shelf_proxy: ^1.0.1
  shelf_web_socket: ^1.0.1
  nanoid: ^1.0.0
  freezed_annotation:
  json_annotation:
  idb_shim: ^2.0.1
  drift: ^1.3.0

  leto_shelf:
  leto_schema:
  leto:

  artemis: ^7.3.0-beta
  equatable: ^2.0.3

dev_dependencies:
  build_runner:
  build_test:
  test:
  build_web_compilers:
  lints: ^1.0.0
  freezed:
  json_serializable:
  drift_dev: ^1.3.0

  leto_generator:

dependency_overrides:
  # leto_generator:
  #   git:
  #     url: https://github.com/juancastillo0/leto
  #     path: leto_generator
  # leto_shelf:
  #   git:
  #     url: https://github.com/juancastillo0/leto
  #     path: leto_shelf
  # leto_schema:
  #   git:
  #     url: https://github.com/juancastillo0/leto
  #     path: leto_schema
  # leto:
  #   git:
  #     url: https://github.com/juancastillo0/leto
  #     path: leto

  # gql:
  #   path: ../../gql/gql
  # gql_code_builder:
  #   path: ../../gql/codegen/gql_code_builder

  leto_generator:
    path: ../../leto/leto_generator
  leto_shelf:
    path: ../../leto/leto_shelf
  leto_schema:
    path: ../../leto/leto_schema
  leto:
    path: ../../leto/leto
