name: bootstrap_dart_example
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  mobx:
  incremental_dom_bindings: ^2.1.0
  universal_html: ^2.0.8
  deact:
    # git:
    #   url: https://github.com/juancastillo0/deact.git
    #   ref: d884bdd0a44e4e3098def601fc5a5f48a7349706
    path: ../../deact
  bootstrap_dart:
    path: ../
  shelf:
  shelf_router:
  shelf_hotreload:
  shelf_proxy: ^1.0.1

dev_dependencies:
  build_runner: ^1.10.0
  build_test: ^1.0.0
  test: ^1.0.0
  build_web_compilers: ^2.11.0
  lints: ^1.0.0
