name: bootstrap_dart_example
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  mobx:
  incremental_dom_bindings: ^2.1.0
  universal_html: ^2.0.8
  deact:
    # git:
    #   url: https://github.com/juancastillo0/deact.git
    #   ref: d884bdd0a44e4e3098def601fc5a5f48a7349706
    path: ../../deact
  bootstrap_dart:
    path: ../
  shelf:
  shelf_router:
  shelf_hotreload:
  shelf_proxy: ^1.0.1
  shelf_web_socket: ^1.0.1
  nanoid: ^1.0.0
  freezed_annotation:
  json_annotation:
  idb_shim: ^2.0.1
  drift: ^1.3.0

dev_dependencies:
  build_runner:
  build_test:
  test:
  build_web_compilers:
  lints: ^1.0.0
  freezed:
  json_serializable:
  drift_dev: ^1.3.0
