name: bootstrap_dart
description: Bootstrap web components for Dart web apps.
version: 1.0.0
homepage: https://github.com/juancastillo0/bootstrap_dart

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  universal_html: ^2.0.8
  js: ^0.6.4

dev_dependencies:
  # TODO:
  # build_runner: ^2.2.0
  # build_test: ^2.1.5
  # test: ^1.21.4
  # build_web_compilers: ^3.2.5
  # lints: ^2.0.0
  build_runner: ^1.10.0
  build_test: ^1.0.0
  test: ^1.0.0
  build_web_compilers: ^2.11.0
  lints: ^2.0.0
  sass_builder: ^2.1.2

  incremental_dom_bindings: ^2.1.0
  mobx: ^2.0.7+5
  highlight: ^0.7.0
  deact:
    git:
      url: https://github.com/juancastillo0/deact.git
      ref: 537a9e600641a0aed15b7811c61f80fe4c0c0d12
    # path: ../deact
  deact_bootstrap:
    path: packages/deact_bootstrap
