name: virtual_web
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  mobx:
  highlight: ^0.7.0
  incremental_dom_bindings: ^2.1.0
  deact:
    git:
      url: https://github.com/juancastillo0/deact.git
      ref: ec5d8fa0fd9aff0dc90e5823cb9efa1c3c2c6325
    # path: ../deact

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  lints: ^1.0.0
